document.write("Result:");
document.write("<br><br/>");
document.write("The value of a is : 7");
document.write("<br><br/>");
document.write("....................................");
document.write("<br><br/>");

var a = 7;
++a;
document.write(`The Value of ++a is: ${a}`);
document.write("<br><br/>");
document.write(`Now the Value of a is: ${a}`);
document.write("<br><br/>");
document.write("<br><br/>");
document.write(`The Value of a++ is: ${a}`);
document.write("<br><br/>");
a++;
document.write(`Now the Value of a is: ${a}`);
document.write("<br><br/>");
document.write("<br><br/>");
--a;
document.write(`the Value of --a is: ${a}`);
document.write("<br><br/>");
document.write(`Now the Value of a is: ${a}`);
document.write("<br><br/>");
document.write("<br><br/>");
a--;
document.write(`the Value of a-- is: ${a}`);
document.write("<br><br/>");
document.write(`Now the Value of a is: ${a}`);
